### PR TITLE
Improve multi-cluster support by prefixing cluster name in TLS provider names and kubeconfigs.

### PR DESCRIPTION
**Pull request by madhusudancs**

### CODE REVIEW

**Comment by colemickens** [comment]
So you're going to support multiclusters but all of the state information is still going to be shared across them in the various `.tmp` dirs through the repo?

I still think a more complete version of this is to have a top level `clusters/` directory with each clusters state stored inside, but that's a much bigger change and has its own challenges.

I need to do something like this for Azure too.... if you change the cluster_name now you get conflicts -- I assume that's what prompted this PR for GCE...

**Comment by madhusudancs** [comment]
> So you're going to support multiclusters but all of the state information is still going to be shared across them in the various .tmp dirs through the repo?

Right now, I am keeping all the generated artifacts in the same directory. It will be much more clear when I send the follow up PRs, but you can see the work here now - https://github.com/madhusudancs/kubernetes-anywhere/tree/federation/federation

> I still think a more complete version of this is to have a top level clusters/ directory with each clusters state stored inside, but that's a much bigger change and has its own challenges.

I am not very sure about this. It makes it difficult to deploy clusters in parallel and have the console output make sense to the users, unless there is a way to supply multiple directories to `terraform apply`.

> I need to do something like this for Azure too.... if you change the cluster_name now you get conflicts -- I assume that's what prompted this PR for GCE...

Yeah. I should have made this for Azure too. Sorry my fault. I will update this PR.

**Comment by colemickens** [comment]
I see, I was thinking about standalone independent clusters. I see why this strategy makes sense for federation scenario. I'll try to find some time to dig into your federation branch, thanks!

**Comment by madhusudancs** [comment]
@colemickens I added Azure changes (I accidentally folded those changes in to the same commit, sorry). PTAL.

**Comment by colemickens** [comment]
This change doesn't break Azure, but I'm not sure if it's enough to fix the federation scenario you're working on.

I think Azure would need to have each resource name (in Terraform) to include the `cluster_name` right? Otherwise Terraform will complain about multiple resources with the same name.

No reason to block this change, just trying to understand.

**Comment by madhusudancs** [comment]
> I think Azure would need to have each resource name (in Terraform) to include the cluster_name right? Otherwise Terraform will complain about multiple resources with the same name.

@colemickens This is true. I do not understand Terraform's Azure directives fully to fix this yet. I would appreciate some help, but I could do it too sometime after all my federation changes are in.

**Comment by colemickens** [comment]
It should just be a matter of weaving the cluster_name into the actual resource names in the Azure terraform. So rather than `azurerm_resource_group.rg` it would be `azurerm_resource_group.{cluster_name}_resource_group` or something.

It seemed too tedious to do a while back, but it sounds like it's going to be needed for federation support. (I know very little about federation and haven't done any Azure testing with it). I can do it at some point... just pretty busy right now.

**Comment by madhusudancs** [comment]
@colemickens fair enough. Let's see who gets to it first.

**Comment by madhusudancs** [comment]
@colemickens I will ping you for help/review if I get to it first.

**Comment by colemickens** [comment]
👍 LGTM on this PR.

**Comment by mikedanese** [comment]
Ugh, let's delete .travis.yml

**Comment by madhusudancs** [comment]
@mikedanese thanks (and also thanks for removing travis checks).

**Pull request merged**
