### PR TITLE
415 - special characters need escaping in vsphere.conf, escapeStringJ…

### PR DESCRIPTION
**Pull request by jck-ccl**
…son seems to do this nicely

#415 proposed fix for escaping special characters in vsphere.conf.

### CODE REVIEW

**Comment by jck-ccl** [comment]
cncf-cla should be signed now.

**Comment by divyenpatel** [comment]
Thanks @jck-ccl for fixing this issue. Change looks good to me.

@tusharnt @BaluDontu

**Comment by jck-ccl** [comment]
Thanks for the quick review! I guess someone with write access needs to merge?

**Comment by divyenpatel** [comment]
@kerneltime @abrarshivani Can you help merging this PR?

**Pull request merged**
