### PR TITLE
Change default nodes to 3 to suit trial size GCE account

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

### CODE REVIEW

**Comment by cmluciano** [comment]
cc @mikedanese @luxas

**Comment by roberthbailey** [comment]
Do we create a single-node master? We'd like to move kubeadm (and also kubernetes-anywhere) to create self-hosted HA masters, at which point we need 3 VMs just for the control plane.

**Comment by pipejakob** [comment]
@roberthbailey Yes, only a single node for the master now.

**Pull request merged**
