### PR TITLE
azure : Rebase ephemeral & premium Disks options 

### PR DESCRIPTION
**Pull request by theobolo**
Hello guys,

@colemickens @mikedanese 

I rebased a little bit the Cole's PR about implementation of ephemeral and premium disks on Azure. I need to work a little bit on it so please DO NOT MERGE for the moment ;)

Some points that are not working for the moment : 
- Implementation of `cfg.phase1.azure.use_premium_storage` and `cfg.phase1.azure.use_ephemeral_drive` was made with a `String` type with choice : `yes` or `no`. Actually the condition :  

>  local storage_type = if cfg.azure.use_premium_storage == "yes" then "Premium_LRS" else "Standard_LRS";

into `azure.jsonnet` is not working with a `bool` type if is setted on "n". The line is commented into the `.config` ...
- The condition `if` into the `phase2/ignition/vanilla/node.jsonnet` is not working properly, i'm not an expert in `jsonnet` and actually if i hit the condition by putting `cfg.phase1.azure.use_ephemeral_drive == yes` the Ignition init crashed on the nodes and throw an error. My `if` condition is certainly badly placed ... 

@mikedanese  you did something similar in the phase3, with `bool` type (addons) but i wasn't able to make it works on the phase1 for Azure. Terraform is still dropping an error saying that `use_ephemeral_drive` is not defined or missing. Cole thinked about a specific problem into Kconfig-conf, but since i saw that you handled it into phase3 maybe that you have the solution.

By the way, use_premium_storage is working properly, the rest needs just some fixes.

Waiting for your review guys, 

Cheers, 
Théo

### CODE REVIEW

**Comment by theobolo** [comment]
I signed it!

**Comment by colemickens** [comment]
This is blocked by #229. I've spent hours trying to fix it by trying different versions of kconfig and different ways of invoking it. It just seems to not work the way I expect and I don't know how to fix it without replacing kconfig config menu system with something entirely different.

**Comment by theobolo** [comment]
Don't loose your time on it ... I'll try to move on ACS soon as possible. By the way i need to implement that on ACS engine Too xD (ACS + Kubernetes is using kubernetes-anywhere ?).

I'm already able to use ephemeral by using a non-Boolean choice in the Kconfig ... that's the only solution i found.

**Comment by kerneltime** [comment]
No activity since a long time.. closing the PR

**Pull request closed without merging**
