### PR TITLE
Mount the /dev directory in the kubelet container so that it can detect persistent disks.

### PR DESCRIPTION
**Pull request by madhusudancs**
This seems to work.

### CODE REVIEW

**Comment by colemickens** [comment]
This is a bit related to #162. Should we have a recommended, documented way to run containerized kubelet with a description of what/why certain paths need to be mounted as volumes (wth an understanding that changing the recommended docker args for `kubelet` includes changing it here and in `kubernetes/kube-deploy/docker-multinode` ? Or is it hopeless to try to wrangle the args even across `kubernetes/*` repos?

**Comment by madhusudancs** [comment]
@colemickens I think it makes sense to keep the flags consistent across scripts/repos that run kubelet inside a containers. They all more or less run into similar problems otherwise. Definitely a +1 for documenting the flag values.

**Comment by mikedanese** [comment]
Lgtm

**Comment by madhusudancs** [comment]
Thanks! Merging the PR.

**Pull request merged**
