### PR TITLE
delete non ignition phase1 compatible stuff and redo docs.

### PR DESCRIPTION
**Pull request by mikedanese**
Still quite a bit of work to do on this one but opening now for visibility

### CODE REVIEW

**Comment by mikedanese** [comment]
@colemickens You have a todo after this :)

**Comment by colemickens** [comment]
@mikedanese ack'd. "getting started guide" is in progress right now, aiming to send a PR this evening. 

Looks like we're nesting them down in phase1/<provider>/README.md ? That's fine, I'll cleanup the basically empty top-level `docs` dir that snuck in my last PR...

**Comment by mikedanese** [comment]
Oops. I'm open to either location.

**Comment by colemickens** [comment]
If I carry forward the "deploy dir per cluster_name" idea, then it would actually be neat to have the README be an artifact that is persisted as part of the cluster deployment. That way it remains accurate for that cluster that was deployed, even in the instructions have changed for newer clusters.

**Pull request merged**
