### PR TITLE
Fix typo under the Phase 3 header

### PR DESCRIPTION
**Pull request by benjaminknox**

### CODE REVIEW

**Comment by errordeveloper** [comment]
@benjaminknox could you please sign the CLA? thanks!

**Comment by benjaminknox** [comment]
@errordeveloper I do actually want to, but the link doesn't go to the wiki and I can't find the wiki

**Comment by errordeveloper** [comment]
It must had been closed down recently...

**Comment by errordeveloper** [comment]
@spiffxp please see the CLA wiki link...

**Comment by benjaminknox** [comment]
:)

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Whoops, sorry for not catching this way, way earlier. The bot was updated to link to the correct page a while back, here's the correct link: https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement

**Comment by benjaminknox** [comment]
Oh, sweet, thanks, I will sign the license agreement soon

**Comment by benjaminknox** [comment]
@errordeveloper, I signed a CLA

**Pull request merged**
