### PR TITLE
Update terraform to 0.9.4

### PR DESCRIPTION
**Pull request by MohGeek**
This updates the Terraform version used by project from 0.7.2 to 0.9.4. It fixes multiple issues related to Terraform (see : https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md). 

- As the cert request flow changed after the 0.7.5 version, the jsonnet had to be updated to reflect this change. 
- The env variable TERRAFORM_SHA256SUM was also deleted from the docker-build script as it wasn't used.

### CODE REVIEW

**Comment by MohGeek** [comment]
I signed it!

**Comment by mikedanese** [comment]
This is probably going to break e2e when it merges. We will need to update:

https://github.com/kubernetes/test-infra/blob/master/images/ci-kubernetes-e2e-kubeadm/Dockerfile#L27

**Comment by pipejakob** [comment]
Thanks for taking this on, @MohGeek! I don't fully grok the jsonnet diff, but I can at least do some independent testing to confirm that things still work.

**Comment by pipejakob** [comment]
Did you test this with `ignition`? Things look good with `phase2.provider=kubeadm`, but I'm not seeing the control plane ever come up when using ignition. Do you have a `.config` file that works (in particular, the `.phase2.installer_container`)?

**Comment by MohGeek** [comment]
Hi @pipejakob, yes, I was able to test this with `ignition` on `vSphere` with the following configuration : 
```
#
# Phase 2: Node Bootstrapping
#
.phase2.installer_container="docker.io/cnastorage/k8s-ignition:v1"
.phase2.docker_registry="gcr.io/google-containers"
.phase2.kubernetes_version="v1.5.3"
.phase2.provider="ignition"
```

**Comment by pipejakob** [comment]
Ah, thank you. It seems my issue was testing your patch with a 1.6.x release, since it looks like our ignition phase2 configuration tries to use flags that are no [longer valid for kubelet 1.6](https://github.com/kubernetes/kubernetes-anywhere/issues/378), so it's broken anyway. Also, our ignition phase2 currently uses hyperkube, which seems to be [unmaintained](https://github.com/kubernetes/dashboard/issues/1710), so it might be time to consider it deprecated in favor of kubeadm anyway (unless someone wants to give it a lot of love).

/lgtm

I'll handle updating the kubeadm e2e image. Our e2e jobs are currently pinned to a fork of k8s-anywhere, so your commit shouldn't break them. Thanks again for taking this on!

**Pull request merged**
