### PR TITLE
Make validate only allow Ready nodes, not NotReady ones

### PR DESCRIPTION
**Pull request by luxas**
@shashidharatd @pipejakob @jessicaochen @roberthbailey 
Fixes the incorrect behavior we noted earlier

### CODE REVIEW

**Comment by luxas** [comment]
@kubernetes/kubernetes-anywhere-maintainers can you merge this please?

**Comment by shashidharatd** [comment]
@luxas, This fix almost same as https://github.com/kubernetes/kubernetes-anywhere/pull/428/files, and we didn't go ahead with that PR because of an issue which is mentioned in there. here is the link to the comment https://github.com/kubernetes/kubernetes-anywhere/pull/428#issuecomment-323999941

**Comment by shashidharatd** [comment]
So i am moving over the discussion from #428
> Why is validate run before addons..?

validate is run before addons because i guess it is expected that kube cluster is up and running (atleast the api-server should be reachable) before addons or deployed.

We need 2 types of validations:
1. which can be run immediately after phase2 to just ensure cluster is up and we can issue commands to the cluster via kubectl.
2. which can be run after running addons to verify all the nodes in Ready condition.

**Comment by luxas** [comment]
So why not add a variable like `REQUIRE_NODES_READY` or something to be able to toggle between these states of readiness?

**Comment by shashidharatd** [comment]
> So why not add a variable like REQUIRE_NODES_READY or something to be able to toggle between these states of readiness?

@luxas, you are exactly right. that's probably the way to fix this. i have raised a patch for this https://github.com/kubernetes/kubernetes-anywhere/pull/447. PTAL

**Comment by luxas** [comment]
Thanks, then closing this one

**Pull request closed without merging**
