### PR TITLE
[wip] Azure: Enable SSD and Docker storage on ephemeral drive

### PR DESCRIPTION
**Pull request by colemickens**
This builds on top of https://github.com/kubernetes/kubernetes-anywhere/pull/157

The diff (the latest commit) enables Premium storage in Azure, and mounts the ephemeral drive to /var/lib/docker. It's wiped on every boot for a few reasons, but it's fine for Kubernetes purposes and speeds things up quite a bit.

CC @theobolo

Theo, this differs from your fork in one way: I do the ephemeral drive configuration in Ansible rather than in `configure-vm.sh`; although I realize that means the intial Ansible container is still a bit slow... I feel it's the more appropriate place to do that sort of change.

Obviously shouldn't be merged until we decide some other things; this will have to change if we move to Ignition, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes-anywhere/185)

### CODE REVIEW

**Comment by theobolo** [comment]
Yep that's better to put directly the config as an option during the Ansible deployment, great job !

And you can say that the Ephemerial SSDs are giving a big speed improvement to the entire cluster :P the image Pull is 4x or 5x times faster and the Deletion / Creation / Updated on controllers are amazingly fast. Using that with the Premium Storage ... and the cluster become "Flash Gordon"

**Comment by theobolo** [comment]
Need to be rebased - i'll try to do something ...

By the way how can we start to handle the specific azure ignition tasks since that for the moment if i get it : the vanilla (phase2) folder is common for gce and Azure bring-ups. 

I made a condition and added two files to handle the ephemerial mounting pushed to /etc/systemd/system/ , then added them to the nodes.jsonnet using the condition Cole used ```phase1.azure.use_ephemeral_drive```.

What do you guys have in mind about the phase2 folder ? still keeping one vanilla folder with some conditions within the jsonnet ?

**Comment by colemickens** [comment]
Yes, that is how I implemented this when using Ansible. It was still a shared playbook, but the tasks were only run when cloud_provider was Azure, and only when the specific option was enabled.

I presume some sort of logic like that is still available in Ignition, but I'm not completely sure. Mike might have thoughts or we may need to consult the Ignition docs more. I can't remember when `jsonnet` is evaluated in the context of Ignition. If `jsonnet` is executed inside the live container, rather than during the container build... then it should be possible to do such logic inside the jsonnet file.

Hopefully that makes sense, I won't be able to look at this more directly for at least a few weeks.

**Comment by theobolo** [comment]
Ok Cole i made something yesterday that's working properly with ignition. That's of course still possible to make some conditions with ignition node and master startup files. 

I'm still working on this a little bit to be able to maybe submit a Pull request correctly :P

**Comment by theobolo** [comment]
Guys why changing the node.jsonnet is impacting nothing ? even if i do ```make clean``` into the Git repo and into the live container ? 

Also tried to delete all docker images made and running containers, but nothing that i add to the node.jsonnet is working :/

**Comment by theobolo** [comment]
I'm a little bit stuck with ignition;

For the moment the `var-lib-docker.mount` and `format-ephemeral.service` are correctly pushed to `/etc/systemd/system` when the ignition container is starting. 

I didn't find how to reproduce the `systemctl reload-daemon` and i think i got a problem with the fact that docker is already installed and mounted on `/dev/sda1`. Since i'm doing the mounting stuff inside a container i think that's not gonna end up correctly :/ 

I can't start mounting of /var/lib/docker before docker.service.  

I made few changes on my branch `rebase_ephemeral` : https://github.com/theobolo/kubernetes-anywhere/tree/rebase_ephemeral 

For the moment kubelet still deploying correctly and the files are not started, seems that `systemctl` don't start anything before `kubelet.service` in `node.jsonnet`.

**Pull request closed without merging**
